Добавил функцию вычисления треугольника.
Igor-NF/Super-math2 pull request #4
Opened 2023-12-10 23:37 UTC by IgorNikF

Посмотри мою функцию пожалуйста.

2023-12-10 23:47 UTC, Igor-NF requested changes
Необходимо поменять логику функции.

2023-12-10 23:47 UTC, Igor-NF commented on src/modules/perimeter.py
> +    return a + b + c
А если это будет другая фигура, прямоугольник например?

2023-12-10 23:52 UTC, IgorNikF commented on src/modules/perimeter.py
> +    return a + b + c
Хорошо, я перепишу эту функцию.

2023-12-11 00:06 UTC, Igor-NF requested changes
Функция написанна верно.
Добавь её в файл main.py.

2023-12-11 00:24 UTC, Igor-NF approved these changes
Всё супер. Спасибо.

2023-12-11 00:27 UTC, merged